create table "public"."makers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."makers" enable row level security;

create table "public"."organization_units" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "organization_id" bigint
);


alter table "public"."organization_units" enable row level security;

create table "public"."organizations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."organizations" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "username" text,
    "full_name" text,
    "avatar_url" text,
    "website" text,
    "organization_id" bigint
);


alter table "public"."profiles" enable row level security;

create table "public"."vehicles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "plate_number" text,
    "maker_id" bigint not null,
    "organization_unit_id" bigint not null
);


alter table "public"."vehicles" enable row level security;

CREATE UNIQUE INDEX makers_pkey ON public.makers USING btree (id);

CREATE UNIQUE INDEX organization_units_pkey ON public.organization_units USING btree (id);

CREATE UNIQUE INDEX organizations_pkey ON public.organizations USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX vehicles_pkey ON public.vehicles USING btree (id);

alter table "public"."makers" add constraint "makers_pkey" PRIMARY KEY using index "makers_pkey";

alter table "public"."organization_units" add constraint "organization_units_pkey" PRIMARY KEY using index "organization_units_pkey";

alter table "public"."organizations" add constraint "organizations_pkey" PRIMARY KEY using index "organizations_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."vehicles" add constraint "vehicles_pkey" PRIMARY KEY using index "vehicles_pkey";

alter table "public"."organization_units" add constraint "organization_units_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."organization_units" validate constraint "organization_units_organization_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."profiles" validate constraint "profiles_organization_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(username) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

alter table "public"."vehicles" add constraint "vehicles_maker_id_fkey" FOREIGN KEY (maker_id) REFERENCES makers(id) not valid;

alter table "public"."vehicles" validate constraint "vehicles_maker_id_fkey";

alter table "public"."vehicles" add constraint "vehicles_organization_unit_id_fkey" FOREIGN KEY (organization_unit_id) REFERENCES organization_units(id) not valid;

alter table "public"."vehicles" validate constraint "vehicles_organization_unit_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

grant delete on table "public"."makers" to "anon";

grant insert on table "public"."makers" to "anon";

grant references on table "public"."makers" to "anon";

grant select on table "public"."makers" to "anon";

grant trigger on table "public"."makers" to "anon";

grant truncate on table "public"."makers" to "anon";

grant update on table "public"."makers" to "anon";

grant delete on table "public"."makers" to "authenticated";

grant insert on table "public"."makers" to "authenticated";

grant references on table "public"."makers" to "authenticated";

grant select on table "public"."makers" to "authenticated";

grant trigger on table "public"."makers" to "authenticated";

grant truncate on table "public"."makers" to "authenticated";

grant update on table "public"."makers" to "authenticated";

grant delete on table "public"."makers" to "service_role";

grant insert on table "public"."makers" to "service_role";

grant references on table "public"."makers" to "service_role";

grant select on table "public"."makers" to "service_role";

grant trigger on table "public"."makers" to "service_role";

grant truncate on table "public"."makers" to "service_role";

grant update on table "public"."makers" to "service_role";

grant delete on table "public"."organization_units" to "anon";

grant insert on table "public"."organization_units" to "anon";

grant references on table "public"."organization_units" to "anon";

grant select on table "public"."organization_units" to "anon";

grant trigger on table "public"."organization_units" to "anon";

grant truncate on table "public"."organization_units" to "anon";

grant update on table "public"."organization_units" to "anon";

grant delete on table "public"."organization_units" to "authenticated";

grant insert on table "public"."organization_units" to "authenticated";

grant references on table "public"."organization_units" to "authenticated";

grant select on table "public"."organization_units" to "authenticated";

grant trigger on table "public"."organization_units" to "authenticated";

grant truncate on table "public"."organization_units" to "authenticated";

grant update on table "public"."organization_units" to "authenticated";

grant delete on table "public"."organization_units" to "service_role";

grant insert on table "public"."organization_units" to "service_role";

grant references on table "public"."organization_units" to "service_role";

grant select on table "public"."organization_units" to "service_role";

grant trigger on table "public"."organization_units" to "service_role";

grant truncate on table "public"."organization_units" to "service_role";

grant update on table "public"."organization_units" to "service_role";

grant delete on table "public"."organizations" to "anon";

grant insert on table "public"."organizations" to "anon";

grant references on table "public"."organizations" to "anon";

grant select on table "public"."organizations" to "anon";

grant trigger on table "public"."organizations" to "anon";

grant truncate on table "public"."organizations" to "anon";

grant update on table "public"."organizations" to "anon";

grant delete on table "public"."organizations" to "authenticated";

grant insert on table "public"."organizations" to "authenticated";

grant references on table "public"."organizations" to "authenticated";

grant select on table "public"."organizations" to "authenticated";

grant trigger on table "public"."organizations" to "authenticated";

grant truncate on table "public"."organizations" to "authenticated";

grant update on table "public"."organizations" to "authenticated";

grant delete on table "public"."organizations" to "service_role";

grant insert on table "public"."organizations" to "service_role";

grant references on table "public"."organizations" to "service_role";

grant select on table "public"."organizations" to "service_role";

grant trigger on table "public"."organizations" to "service_role";

grant truncate on table "public"."organizations" to "service_role";

grant update on table "public"."organizations" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."vehicles" to "anon";

grant insert on table "public"."vehicles" to "anon";

grant references on table "public"."vehicles" to "anon";

grant select on table "public"."vehicles" to "anon";

grant trigger on table "public"."vehicles" to "anon";

grant truncate on table "public"."vehicles" to "anon";

grant update on table "public"."vehicles" to "anon";

grant delete on table "public"."vehicles" to "authenticated";

grant insert on table "public"."vehicles" to "authenticated";

grant references on table "public"."vehicles" to "authenticated";

grant select on table "public"."vehicles" to "authenticated";

grant trigger on table "public"."vehicles" to "authenticated";

grant truncate on table "public"."vehicles" to "authenticated";

grant update on table "public"."vehicles" to "authenticated";

grant delete on table "public"."vehicles" to "service_role";

grant insert on table "public"."vehicles" to "service_role";

grant references on table "public"."vehicles" to "service_role";

grant select on table "public"."vehicles" to "service_role";

grant trigger on table "public"."vehicles" to "service_role";

grant truncate on table "public"."vehicles" to "service_role";

grant update on table "public"."vehicles" to "service_role";

create policy "Public profiles are viewable by everyone."
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Users can insert their own profile."
on "public"."profiles"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Users can update own profile."
on "public"."profiles"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = id));



